
<?php
    $_productCollection=$this->getLoadedProductCollection();
    //var_dump($this->gettabtype());die;
   // echo $_productCollection->getSelect();die;
    $_helper = $this->helper('catalog/output');	
    $image_product_hover = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId); 
    $ajax_cart		 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
 $quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId); 
   $thumb_width=500;
   $thumb_height=500;
   $cpBlock = $this->getLayout()->getBlockSingleton('EuropeSoft_OptionConfigurable_Block_Product_View_Js'); 
?>
<?php if(!count($_productCollection)):  ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    
    
    <?php if(Mage::getStoreConfig('ajaxhometabs/'.$this->gettabtype().'/view_mode')=='list'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>		
		<?php 
                
                if($this->gettabtype()=='topbestsell'){
			
				$productid=null;
			        $configurableProduct = Mage::getModel('catalog/product_type_configurable');
                                
				$parentIdArray = $configurableProduct->getParentIdsByChild($_product->getProductId());
				    
				    //if simple product belong to configurable product
				    if (!empty($parentIdArray))
				    {
				        $parentProduct = Mage::getModel('catalog/product')->load($parentIdArray[0]);
				    if($parentProduct->getTypeId() == 'configurable' )
					{
						 $productid=$parentProduct->getEntityId();						
					};
					}else      
       				$productid=$_product->getProductId();
			        
			
			if($productid!= null)
			    $_product=Mage::getModel('catalog/product')->load($productid);
			
		}elseif($this->gettabtype()=='toprate'||$this->gettabtype()=='topreview'){
			$_product=Mage::getModel('catalog/product')->load($_product->getEntityId());
			
		};
		?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image var_dump
            ?>
            <div class="nova-product-images">
                <?php include('view/labels.phtml')  ?> 
                 <?php 
                            $_product->setDoNotUseCategoryId(false);
                            $categoryIds = $_product->getCategoryIds();
                            //if you are sure that the product is in one category and only one skip the next lines. If not, you can get the id of the lowest level like you do
                            $cats_collection = Mage::getModel('catalog/category')->getCollection()
                                    ->addAttributeToFilter('entity_id', $categoryIds)
                                    ->addAttributeToFilter('is_active', 1);
                            // I filter the categories by their level, so they always go cat/sub-cat/sub-sub-cat 
                            $cats_collection->getSelect()->order('level DESC')->limit(1);
                            //no register the category so it can be used in the product url:
                            $registeredCategory = Mage::registry('current_category');
                            Mage::unregister('current_category');//use this to avoid registry errors
                            Mage::register('current_category', $cats_collection->getFirstItem());
                            $url = $_product->getProductUrl();//this is the product url.
                            
                            Mage::unregister('current_category');//reset the registry to previous state.
                            if (registeredCategory){
                                Mage::register('current_category', registeredCategory);
                            }
                  ?>
                <a href="<?php echo $url; ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                       <?php 
                        if($image_product_hover) { ?>
                        <div class="front">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </div>
                        <?php
                         $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
                         foreach ($_gallery as $_image ):
                         ?>
                         <div class="product-img-additional back">
                         <img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                         </div>
                         <?php
                                        break;
                                        endforeach;
                        ?>
                        <?php
                        }else{
                        ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                        <?php	
                        }
                        ?>
                                                
                
                </a>
            </div>
            
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					
                    <?php //if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php //endif; ?>
                    
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>
 <?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    				<?php
                                
                                $t = Mage::getModel('catalog/product')->load($_product->getId());
                                
                                if($this->gettabtype()=='topbestsell'){
			
                                    $productid=null;
                                   $configurableProduct = Mage::getModel('catalog/product_type_configurable');
                                    $parentIdArray = $configurableProduct->getParentIdsByChild($_product->getProductId());
				    
				    //if simple product belong to configurable product
				    if (!empty($parentIdArray))
				    {
				        $parentProduct = Mage::getModel('catalog/product')->load($parentIdArray[0]);
				    if($parentProduct->getTypeId() == 'configurable' )
					{
						 $productid=$parentProduct->getEntityId();						
					};
					}else      
       				$productid=$_product->getProductId();
			
			     
                               
			if($productid!= null)
			$_product=Mage::getModel('catalog/product')->load($productid);
			
		}elseif($this->gettabtype()=='toprate'||$this->gettabtype()=='topreview'){
			$_product=Mage::getModel('catalog/product')->load($_product->getEntityId());
			
		};
		?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
       
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                
                    <div class="nova-product-images">
                        <?php include('view/labels.phtml')  ?> 
                         <?php 
                            $_product->setDoNotUseCategoryId(false);
                            $categoryIds = $_product->getCategoryIds();
                            //if you are sure that the product is in one category and only one skip the next lines. If not, you can get the id of the lowest level like you do
                            $cats_collection = Mage::getModel('catalog/category')->getCollection()
                                    ->addAttributeToFilter('entity_id', $categoryIds)
                                    ->addAttributeToFilter('is_active', 1);
                            // I filter the categories by their level, so they always go cat/sub-cat/sub-sub-cat 
                            $cats_collection->getSelect()->order('level DESC')->limit(1);
                            //no register the category so it can be used in the product url:
                            $registeredCategory = Mage::registry('current_category');
                            Mage::unregister('current_category');//use this to avoid registry errors
                            Mage::register('current_category', $cats_collection->getFirstItem());
                            $url = $_product->getProductUrl();//this is the product url.
                            
                            Mage::unregister('current_category');//reset the registry to previous state.
                            if (registeredCategory){
                                Mage::register('current_category', registeredCategory);
                            }
                  ?>
                     <a href="<?php echo $url ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                       <?php 
                        if($image_product_hover) { ?>
                        <div class="front">
                            <img id="<?php echo $_product->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </div>
                        <?php
                         $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
                         foreach ($_gallery as $_image ):
                         ?>
                         <div class="product-img-additional back">
                         <img style="height:221px;" src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                         </div>
                         <?php
                                        break;
                                        endforeach;
                        ?>
                        <?php
                        }else{
                        ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                        <?php	
                        }
                        ?>
                                                
                
                </a>
            </div>
                
                
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php //endif; ?>
               
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="price-product-box"><?php echo $this->getPriceHtml($_product, true) ?></div>
                <div class="clear"></div>
                 <div class="optionimages" >
                    <?php 

                        $optionImages=$cpBlock->getImages($t,$thumb_width,$thumb_height);

                        foreach ($optionImages as $image){
                    ?>
                    <img src="<?php echo $image['picker']?>" onclick="changeOptionImage('<?php echo  $image['origin'];?>',<?php echo $_product->getId(); ?>)" style="">
                    <?php
                        }
                    ?>
                </div>
                <div class="descriptions-hidden">		
                    <div class="quick-act" id="quick-act-<?php echo $_product->getId()?>">            

                            <?php if($quick_view): ?>
                            <div class="quickview-box">
                                    <a class="" href="<?php echo $_product->getProductUrl() ?>" data-id="<?php echo $_product->getId()?>"><?php echo $this->__('View')?></a> 
                            </div>
                            <?php endif;?>

                       
                    </div>
              </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

</div>
<?php endif; ?>
<script>
    function changeOptionImage(src,id){
        var x=document.getElementById(id);
        
        x.style.width=x.width+"px";
        x.style.height=x.height+"px";
        x.src=src;
    }
    
</script>