<?php 
    $product=$this->getProduct();
    $randomProductIds=$this->getRandomProductIds($product);
    $i=0;
    $_columnCount=4;
    $image_product_hover = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId); 
    $_helper = $this->helper('catalog/output');	
    $quick_view= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId); 
?>
<div class="category-products">
    <ul class="products-grid">
    <?php foreach ($randomProductIds as $_productId): ?>
    <?php 
       
       $_product= Mage::getModel('catalog/product')->load($_productId);
    ?>
    <li class="item<?php if(($i+1)%$_columnCount==0): ?> last<?php elseif($i%$_columnCount==0): ?> first<?php endif; ?>">
        <div class="nova-product-images">
                  <?php include('view/labels.phtml')  ?> 
                 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                   <?php 
                    if($image_product_hover) { ?>
                    <div class="front">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </div>
                    <?php
                     $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
                     foreach ($_gallery as $_image ):
                     ?>
                     <div class="product-img-additional back">
                     <img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                     </div>
                     <?php
                                    break;
                                    endforeach;
                    ?>
                    <?php
                    }else{
                    ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />

                    <?php	
                    }
                    ?>


            </a>
        </div>
         <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php //endif; ?>
                <div class="price-product-box"><?php echo $this->getPriceHtml($_product, true) ?></div>
                
                <span class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></span>
                <div class="descriptions-hidden">		
                    <div class="quick-act" id="quick-act-<?php echo $_product->getId()?>">            

                            <?php if($quick_view): ?>
                            <div class="quickview-box">
                                    <a class="" href="<?php echo $_product->getProductUrl() ?>" data-id="<?php echo $_product->getId()?>"><?php echo $this->__('View')?></a> 
                            </div>
                            <?php endif;?>


                    </div>
              </div>
    </li>
    <?php $i++; ?>
    <?php endforeach; ?>
    </ul>
</div>

