<?php   
$_product = $this->getProduct();

   $sample_file_link = Mage::getModel('catalog/product')->load($_product->getId())->getData('sample_file_link');
   
   if ($sample_file_link!=""){
?>
    <div class="sample">
        
        <div><img src="<?php echo Mage::getDesign()->getSkinUrl("images/heart.jpg"); ?>"/><a href="<?php echo Mage::getBaseUrl().$sample_file_link;?>">Download Sample</a></div>
    </div>
<?php 
   }
?>