<div class="mini-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    	<div class="shopping-cart">     
		<a class="mini-cart-title" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
			<i class="icon-bag"></i> <?php echo $this->__('Shopping Cart'); ?>       
			<span class="cart_circle<?php if($_cartQty): echo " active"; endif;?>">
			<?php if($_cartQty): echo " ( ".$_cartQty." ) "; endif;?></span>
		</a>
		</div>  
    <?php $_items = $this->getRecentItems(); ?>
    <?php if(count($_items)): ?>
    	<div class="block-content" style="display:block;">
    		<div class="block-content-inner">
	            <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
	            <ol id="cart-sidebar" class="mini-products-list">
	            <?php foreach($_items as $_item): ?>
	                <?php echo $this->getItemHtml($_item) ?>
	            <?php endforeach; ?>
	            </ol>          
	            <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
	            
	            <div class="actions">
	            	<button type="button" title="<?php echo $this->__('View contents of your shopping cart') ?>" class="button btn-inline button-shopcart" onclick="setLocation('<?php echo $this->getUrl('checkout/cart') ?>')"><span><span><?php echo $this->__('View shopping cart') ?></span></span></button>
	            	<button type="button" title="<?php echo $this->__('View contents of your shopping cart') ?>" class="button btn-inline" onclick="setLocation('<?php echo $this->getUrl('checkout/onepage') ?>')"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	            	<?php echo $this->getChildHtml('extra_actions') ?>
	            </div>
			</div>
        </div>
    <?php else: ?>
    	<div class="block-content">
        <div class="block-content-inner">
            	<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
		</div>
		</div>
    <?php endif ?>
</div>
