<?php 
        $currentCat = Mage::registry('current_category');
        if ($currentCat->getLevel()==4){
            $currentCat= $currentCat->getParentCategory();

?>

    <div class="block left-categories">
        <?php 

            echo '<div class="block-title"><span>'.$currentCat->getName().'</span></div>';

            if ( $currentCat->getParentId() == Mage::app()->getStore()->getRootCategoryId() ){
                $loadCategory = $currentCat;
            }else{
                $loadCategory = Mage::getModel('catalog/category')->load($currentCat->getId());
            }
            $subCategories = explode(',', $loadCategory->getChildren());  
            if(count($subCategories) > 1){
              echo '<div class="block-content left-categories-container">';
                echo '<ul>';
                foreach ( $subCategories as $subCategoryId ){
                    $cat = Mage::getModel('catalog/category')->load($subCategoryId);
                    if($cat->getIsActive()){
                        echo '<li><a href="'.$cat->getURL().'">'.$cat->getName().'</a></li>';
                    }
                }
                echo '</ul>';
                echo '</div>';
            }
        ?>
    </div>
<?php 
    }
?>