<?php
/**
 * Mageplace Flash Magazine
 *
 * @category    Mageplace
 * @package     Mageplace_Flashmagazine
 * @copyright   Copyright (c) 2010 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */
?>
<span class="widget flashmagazine-widget-link-image">
	<a <?php echo $this->getLinkAttributes() ?>>
		<img src="<?php echo $this->getThumbUrl(); ?>" width="56" height="56" title="<?php echo $this->htmlEscape($this->getAnchorText()); ?>" alt="<?php echo $this->htmlEscape($this->getAnchorText()); ?>" />
	</a>
</span>
