<?php
/**
 * Mageplace Flash Magazine
 *
 * @category    Mageplace
 * @package     Mageplace_Flashmagazine
 * @copyright   Copyright (c) 2010 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */
?>
<span class="widget flashmagazine-widget-link"><a <?php echo $this->getLinkAttributes(); ?>><span><?php echo $this->htmlEscape($this->getAnchorText()); ?></span></a></span>
