<?php class NovaWorks_ThemeOptions_Model_Fonts
{
    public function toOptionArray()
    {
        return array(
            array('value'=>'', 'label'=>Mage::helper('themeoptions')->__('Default Font')),
            array('value'=>'Abel', 'label'=>Mage::helper('themeoptions')->__('Abel')),
            array('value'=>'Abril Fatface', 'label'=>Mage::helper('themeoptions')->__('Abril Fatface')),
            array('value'=>'Aclonica', 'label'=>Mage::helper('themeoptions')->__('Aclonica')),
            array('value'=>'Acme', 'label'=>Mage::helper('themeoptions')->__('Acme')),
            array('value'=>'Actor', 'label'=>Mage::helper('themeoptions')->__('Actor')),
            array('value'=>'Adamina', 'label'=>Mage::helper('themeoptions')->__('Adamina')),
            array('value'=>'Aguafina Script', 'label'=>Mage::helper('themeoptions')->__('Aguafina Script')),
            array('value'=>'Aladin', 'label'=>Mage::helper('themeoptions')->__('Aladin')),
            array('value'=>'Aldrich', 'label'=>Mage::helper('themeoptions')->__('Aldrich')),
            array('value'=>'Alegreya', 'label'=>Mage::helper('themeoptions')->__('Alegreya')),
            array('value'=>'Alegreya SC', 'label'=>Mage::helper('themeoptions')->__('Alegreya SC')),
            array('value'=>'Alex Brush', 'label'=>Mage::helper('themeoptions')->__('Alex Brush')),
            array('value'=>'Alfa Slab One', 'label'=>Mage::helper('themeoptions')->__('Alfa Slab One')),
            array('value'=>'Alice', 'label'=>Mage::helper('themeoptions')->__('Alice')),
            array('value'=>'Alike', 'label'=>Mage::helper('themeoptions')->__('Alike')),
            array('value'=>'Alike Angular', 'label'=>Mage::helper('themeoptions')->__('Alike Angular')),
            array('value'=>'Allan', 'label'=>Mage::helper('themeoptions')->__('Allan')),
            array('value'=>'Allerta', 'label'=>Mage::helper('themeoptions')->__('Allerta')),
            array('value'=>'Allerta Stencil', 'label'=>Mage::helper('themeoptions')->__('Allerta Stencil')),
            array('value'=>'Allura', 'label'=>Mage::helper('themeoptions')->__('Allura')),
            array('value'=>'Almendra', 'label'=>Mage::helper('themeoptions')->__('Almendra')),
            array('value'=>'Almendra SC', 'label'=>Mage::helper('themeoptions')->__('Almendra SC')),
            array('value'=>'Amaranth', 'label'=>Mage::helper('themeoptions')->__('Amaranth')),
            array('value'=>'Amatic SC', 'label'=>Mage::helper('themeoptions')->__('Amatic SC')),
            array('value'=>'Amethysta', 'label'=>Mage::helper('themeoptions')->__('Amethysta')),
            array('value'=>'Andada', 'label'=>Mage::helper('themeoptions')->__('Andada')),
            array('value'=>'Andika', 'label'=>Mage::helper('themeoptions')->__('Andika')),
            array('value'=>'Annie Use Your Telescope', 'label'=>Mage::helper('themeoptions')->__('Annie Use Your Telescope')),
            array('value'=>'Anonymous Pro', 'label'=>Mage::helper('themeoptions')->__('Anonymous Pro')),
            array('value'=>'Antic', 'label'=>Mage::helper('themeoptions')->__('Antic')),
            array('value'=>'Anton', 'label'=>Mage::helper('themeoptions')->__('Anton')),
            array('value'=>'Arapey', 'label'=>Mage::helper('themeoptions')->__('Arapey')),
            array('value'=>'Arbutus', 'label'=>Mage::helper('themeoptions')->__('Arbutus')),
            array('value'=>'Architects Daughter', 'label'=>Mage::helper('themeoptions')->__('Architects Daughter')),
            array('value'=>'Arimo', 'label'=>Mage::helper('themeoptions')->__('Arimo')),
            array('value'=>'Arizonia', 'label'=>Mage::helper('themeoptions')->__('Arizonia')),
            array('value'=>'Armata', 'label'=>Mage::helper('themeoptions')->__('Armata')),
            array('value'=>'Artifika', 'label'=>Mage::helper('themeoptions')->__('Artifika')),
            array('value'=>'Arvo', 'label'=>Mage::helper('themeoptions')->__('Arvo')),
            array('value'=>'Asap', 'label'=>Mage::helper('themeoptions')->__('Asap')),
            array('value'=>'Asset', 'label'=>Mage::helper('themeoptions')->__('Asset')),
            array('value'=>'Astloch', 'label'=>Mage::helper('themeoptions')->__('Astloch')),
            array('value'=>'Asul', 'label'=>Mage::helper('themeoptions')->__('Asul')),
            array('value'=>'Atomic Age', 'label'=>Mage::helper('themeoptions')->__('Atomic Age')),
            array('value'=>'Aubrey', 'label'=>Mage::helper('themeoptions')->__('Aubrey')),
            array('value'=>'Bad Script', 'label'=>Mage::helper('themeoptions')->__('Bad Script')),
            array('value'=>'Balthazar', 'label'=>Mage::helper('themeoptions')->__('Balthazar')),
            array('value'=>'Bangers', 'label'=>Mage::helper('themeoptions')->__('Bangers')),
            array('value'=>'Basic', 'label'=>Mage::helper('themeoptions')->__('Basic')),
            array('value'=>'Baumans', 'label'=>Mage::helper('themeoptions')->__('Baumans')),
            array('value'=>'Belgrano', 'label'=>Mage::helper('themeoptions')->__('Belgrano')),
            array('value'=>'Bentham', 'label'=>Mage::helper('themeoptions')->__('Bentham')),
            array('value'=>'Bevan', 'label'=>Mage::helper('themeoptions')->__('Bevan')),
            array('value'=>'Bigshot One', 'label'=>Mage::helper('themeoptions')->__('Bigshot One')),
            array('value'=>'Bilbo', 'label'=>Mage::helper('themeoptions')->__('Bilbo')),
            array('value'=>'Bilbo Swash Caps', 'label'=>Mage::helper('themeoptions')->__('Bilbo Swash Caps')),
            array('value'=>'Bitter', 'label'=>Mage::helper('themeoptions')->__('Bitter')),
            array('value'=>'Black Ops One', 'label'=>Mage::helper('themeoptions')->__('Black Ops One')),
            array('value'=>'Bonbon', 'label'=>Mage::helper('themeoptions')->__('Bonbon')),
            array('value'=>'Boogaloo', 'label'=>Mage::helper('themeoptions')->__('Boogaloo')),
            array('value'=>'Bowlby One', 'label'=>Mage::helper('themeoptions')->__('Bowlby One')),
            array('value'=>'Bowlby One SC', 'label'=>Mage::helper('themeoptions')->__('Bowlby One SC')),
            array('value'=>'Brawler', 'label'=>Mage::helper('themeoptions')->__('Brawler')),
            array('value'=>'Bree Serif', 'label'=>Mage::helper('themeoptions')->__('Bree Serif')),
            array('value'=>'Bubblegum Sans', 'label'=>Mage::helper('themeoptions')->__('Bubblegum Sans')),
            array('value'=>'Buda', 'label'=>Mage::helper('themeoptions')->__('Buda')),
            array('value'=>'Buenard', 'label'=>Mage::helper('themeoptions')->__('Buenard')),
            array('value'=>'Butcherman', 'label'=>Mage::helper('themeoptions')->__('Butcherman')),
            array('value'=>'Butterfly Kids', 'label'=>Mage::helper('themeoptions')->__('Butterfly Kids')),
            array('value'=>'Cabin', 'label'=>Mage::helper('themeoptions')->__('Cabin')),
            array('value'=>'Cabin Condensed', 'label'=>Mage::helper('themeoptions')->__('Cabin Condensed')),
            array('value'=>'Cabin Sketch', 'label'=>Mage::helper('themeoptions')->__('Cabin Sketch')),
            array('value'=>'Caesar Dressing', 'label'=>Mage::helper('themeoptions')->__('Caesar Dressing')),
            array('value'=>'Cagliostro', 'label'=>Mage::helper('themeoptions')->__('Cagliostro')),
            array('value'=>'Calligraffitti', 'label'=>Mage::helper('themeoptions')->__('Calligraffitti')),
            array('value'=>'Cambo', 'label'=>Mage::helper('themeoptions')->__('Cambo')),
            array('value'=>'Candal', 'label'=>Mage::helper('themeoptions')->__('Candal')),
            array('value'=>'Cantarell', 'label'=>Mage::helper('themeoptions')->__('Cantarell')),
            array('value'=>'Cardo', 'label'=>Mage::helper('themeoptions')->__('Cardo')),
            array('value'=>'Carme', 'label'=>Mage::helper('themeoptions')->__('Carme')),
            array('value'=>'Carter One', 'label'=>Mage::helper('themeoptions')->__('Carter One')),
            array('value'=>'Caudex', 'label'=>Mage::helper('themeoptions')->__('Caudex')),
            array('value'=>'Cedarville Cursive', 'label'=>Mage::helper('themeoptions')->__('Cedarville Cursive')),
            array('value'=>'Ceviche One', 'label'=>Mage::helper('themeoptions')->__('Ceviche One')),
            array('value'=>'Changa One', 'label'=>Mage::helper('themeoptions')->__('Changa One')),
            array('value'=>'Chango', 'label'=>Mage::helper('themeoptions')->__('Chango')),
            array('value'=>'Chelsea Market', 'label'=>Mage::helper('themeoptions')->__('Chelsea Market')),
            array('value'=>'Cherry Cream Soda', 'label'=>Mage::helper('themeoptions')->__('Cherry Cream Soda')),
            array('value'=>'Chewy', 'label'=>Mage::helper('themeoptions')->__('Chewy')),
            array('value'=>'Chicle', 'label'=>Mage::helper('themeoptions')->__('Chicle')),
            array('value'=>'Chivo', 'label'=>Mage::helper('themeoptions')->__('Chivo')),
            array('value'=>'Coda', 'label'=>Mage::helper('themeoptions')->__('Coda')),
            array('value'=>'Coda Caption', 'label'=>Mage::helper('themeoptions')->__('Coda Caption')),
            array('value'=>'Comfortaa', 'label'=>Mage::helper('themeoptions')->__('Comfortaa')),
            array('value'=>'Coming Soon', 'label'=>Mage::helper('themeoptions')->__('Coming Soon')),
            array('value'=>'Concert One', 'label'=>Mage::helper('themeoptions')->__('Concert One')),
            array('value'=>'Condiment', 'label'=>Mage::helper('themeoptions')->__('Condiment')),
            array('value'=>'Contrail One', 'label'=>Mage::helper('themeoptions')->__('Contrail One')),
            array('value'=>'Convergence', 'label'=>Mage::helper('themeoptions')->__('Convergence')),
            array('value'=>'Cookie', 'label'=>Mage::helper('themeoptions')->__('Cookie')),
            array('value'=>'Copse', 'label'=>Mage::helper('themeoptions')->__('Copse')),
            array('value'=>'Corben', 'label'=>Mage::helper('themeoptions')->__('Corben')),
            array('value'=>'Cousine', 'label'=>Mage::helper('themeoptions')->__('Cousine')),
            array('value'=>'Coustard', 'label'=>Mage::helper('themeoptions')->__('Coustard')),
            array('value'=>'Covered By Your Grace', 'label'=>Mage::helper('themeoptions')->__('Covered By Your Grace')),
            array('value'=>'Crafty Girls', 'label'=>Mage::helper('themeoptions')->__('Crafty Girls')),
            array('value'=>'Creepster', 'label'=>Mage::helper('themeoptions')->__('Creepster')),
            array('value'=>'Crete Round', 'label'=>Mage::helper('themeoptions')->__('Crete Round')),
            array('value'=>'Crimson Text', 'label'=>Mage::helper('themeoptions')->__('Crimson Text')),
            array('value'=>'Crushed', 'label'=>Mage::helper('themeoptions')->__('Crushed')),
            array('value'=>'Cuprum', 'label'=>Mage::helper('themeoptions')->__('Cuprum')),
            array('value'=>'Damion', 'label'=>Mage::helper('themeoptions')->__('Damion')),
            array('value'=>'Dancing Script', 'label'=>Mage::helper('themeoptions')->__('Dancing Script')),
            array('value'=>'Dawning of a New Day', 'label'=>Mage::helper('themeoptions')->__('Dawning of a New Day')),
            array('value'=>'Days One', 'label'=>Mage::helper('themeoptions')->__('Days One')),
            array('value'=>'Delius', 'label'=>Mage::helper('themeoptions')->__('Delius')),
            array('value'=>'Delius Swash Caps', 'label'=>Mage::helper('themeoptions')->__('Delius Swash Caps')),
            array('value'=>'Delius Unicase', 'label'=>Mage::helper('themeoptions')->__('Delius Unicase')),
            array('value'=>'Devonshire', 'label'=>Mage::helper('themeoptions')->__('Devonshire')),
            array('value'=>'Didact Gothic', 'label'=>Mage::helper('themeoptions')->__('Didact Gothic')),
            array('value'=>'Diplomata', 'label'=>Mage::helper('themeoptions')->__('Diplomata')),
            array('value'=>'Diplomata SC', 'label'=>Mage::helper('themeoptions')->__('Diplomata SC')),
            array('value'=>'Dorsa', 'label'=>Mage::helper('themeoptions')->__('Dorsa')),
            array('value'=>'Dr Sugiyama', 'label'=>Mage::helper('themeoptions')->__('Dr Sugiyama')),
            array('value'=>'Droid Sans', 'label'=>Mage::helper('themeoptions')->__('Droid Sans')),
            array('value'=>'Droid Sans Mono', 'label'=>Mage::helper('themeoptions')->__('Droid Sans Mono')),
            array('value'=>'Droid Serif', 'label'=>Mage::helper('themeoptions')->__('Droid Serif')),
            array('value'=>'Duru Sans', 'label'=>Mage::helper('themeoptions')->__('Duru Sans')),
            array('value'=>'Dynalight', 'label'=>Mage::helper('themeoptions')->__('Dynalight')),
            array('value'=>'EB Garamond', 'label'=>Mage::helper('themeoptions')->__('EB Garamond')),
            array('value'=>'Eater', 'label'=>Mage::helper('themeoptions')->__('Eater')),
            array('value'=>'Electrolize', 'label'=>Mage::helper('themeoptions')->__('Electrolize')),
            array('value'=>'Emblema One', 'label'=>Mage::helper('themeoptions')->__('Emblema One')),
            array('value'=>'Engagement', 'label'=>Mage::helper('themeoptions')->__('Engagement')),
            array('value'=>'Enriqueta', 'label'=>Mage::helper('themeoptions')->__('Enriqueta')),
            array('value'=>'Erica One', 'label'=>Mage::helper('themeoptions')->__('Erica One')),
            array('value'=>'Esteban', 'label'=>Mage::helper('themeoptions')->__('Esteban')),
            array('value'=>'Euphoria Script', 'label'=>Mage::helper('themeoptions')->__('Euphoria Script')),
            array('value'=>'Ewert', 'label'=>Mage::helper('themeoptions')->__('Ewert')),
            array('value'=>'Exo', 'label'=>Mage::helper('themeoptions')->__('Exo')),
            array('value'=>'Expletus Sans', 'label'=>Mage::helper('themeoptions')->__('Expletus Sans')),
            array('value'=>'Fanwood Text', 'label'=>Mage::helper('themeoptions')->__('Fanwood Text')),
            array('value'=>'Fascinate', 'label'=>Mage::helper('themeoptions')->__('Fascinate')),
            array('value'=>'Fascinate Inline', 'label'=>Mage::helper('themeoptions')->__('Fascinate Inline')),
            array('value'=>'Federant', 'label'=>Mage::helper('themeoptions')->__('Federant')),
            array('value'=>'Federo', 'label'=>Mage::helper('themeoptions')->__('Federo')),
            array('value'=>'Felipa', 'label'=>Mage::helper('themeoptions')->__('Felipa')),
            array('value'=>'Fjord One', 'label'=>Mage::helper('themeoptions')->__('Fjord One')),
            array('value'=>'Flamenco', 'label'=>Mage::helper('themeoptions')->__('Flamenco')),
            array('value'=>'Flavors', 'label'=>Mage::helper('themeoptions')->__('Flavors')),
            array('value'=>'Fondamento', 'label'=>Mage::helper('themeoptions')->__('Fondamento')),
            array('value'=>'Fontdiner Swanky', 'label'=>Mage::helper('themeoptions')->__('Fontdiner Swanky')),
            array('value'=>'Forum', 'label'=>Mage::helper('themeoptions')->__('Forum')),
            array('value'=>'Francois One', 'label'=>Mage::helper('themeoptions')->__('Francois One')),
            array('value'=>'Fredericka the Great', 'label'=>Mage::helper('themeoptions')->__('Fredericka the Great')),
            array('value'=>'Fresca', 'label'=>Mage::helper('themeoptions')->__('Fresca')),
            array('value'=>'Frijole', 'label'=>Mage::helper('themeoptions')->__('Frijole')),
            array('value'=>'Fugaz One', 'label'=>Mage::helper('themeoptions')->__('Fugaz One')),
            array('value'=>'Galdeano', 'label'=>Mage::helper('themeoptions')->__('Galdeano')),
            array('value'=>'Gentium Basic', 'label'=>Mage::helper('themeoptions')->__('Gentium Basic')),
            array('value'=>'Gentium Book Basic', 'label'=>Mage::helper('themeoptions')->__('Gentium Book Basic')),
            array('value'=>'Geo', 'label'=>Mage::helper('themeoptions')->__('Geo')),
            array('value'=>'Geostar', 'label'=>Mage::helper('themeoptions')->__('Geostar')),
            array('value'=>'Geostar Fill', 'label'=>Mage::helper('themeoptions')->__('Geostar Fill')),
            array('value'=>'Germania One', 'label'=>Mage::helper('themeoptions')->__('Germania One')),
            array('value'=>'Give You Glory', 'label'=>Mage::helper('themeoptions')->__('Give You Glory')),
            array('value'=>'Glegoo', 'label'=>Mage::helper('themeoptions')->__('Glegoo')),
            array('value'=>'Gloria Hallelujah', 'label'=>Mage::helper('themeoptions')->__('Gloria Hallelujah')),
            array('value'=>'Goblin One', 'label'=>Mage::helper('themeoptions')->__('Goblin One')),
            array('value'=>'Gochi Hand', 'label'=>Mage::helper('themeoptions')->__('Gochi Hand')),
            array('value'=>'Goudy Bookletter 1911', 'label'=>Mage::helper('themeoptions')->__('Goudy Bookletter 1911')),
            array('value'=>'Gravitas One', 'label'=>Mage::helper('themeoptions')->__('Gravitas One')),
            array('value'=>'Gruppo', 'label'=>Mage::helper('themeoptions')->__('Gruppo')),
            array('value'=>'Gudea', 'label'=>Mage::helper('themeoptions')->__('Gudea')),
            array('value'=>'Habibi', 'label'=>Mage::helper('themeoptions')->__('Habibi')),
            array('value'=>'Hammersmith One', 'label'=>Mage::helper('themeoptions')->__('Hammersmith One')),
            array('value'=>'Handlee', 'label'=>Mage::helper('themeoptions')->__('Handlee')),
            array('value'=>'Herr Von Muellerhoff', 'label'=>Mage::helper('themeoptions')->__('Herr Von Muellerhoff')),
            array('value'=>'Holtwood One SC', 'label'=>Mage::helper('themeoptions')->__('Holtwood One SC')),
            array('value'=>'Homemade Apple', 'label'=>Mage::helper('themeoptions')->__('Homemade Apple')),
            array('value'=>'Homenaje', 'label'=>Mage::helper('themeoptions')->__('Homenaje')),
            array('value'=>'IM Fell DW Pica', 'label'=>Mage::helper('themeoptions')->__('IM Fell DW Pica')),
            array('value'=>'IM Fell DW Pica SC', 'label'=>Mage::helper('themeoptions')->__('IM Fell DW Pica SC')),
            array('value'=>'IM Fell Double Pica', 'label'=>Mage::helper('themeoptions')->__('IM Fell Double Pica')),
            array('value'=>'IM Fell Double Pica SC', 'label'=>Mage::helper('themeoptions')->__('IM Fell Double Pica SC')),
            array('value'=>'IM Fell English', 'label'=>Mage::helper('themeoptions')->__('IM Fell English')),
            array('value'=>'IM Fell English SC', 'label'=>Mage::helper('themeoptions')->__('IM Fell English SC')),
            array('value'=>'IM Fell French Canon', 'label'=>Mage::helper('themeoptions')->__('IM Fell French Canon')),
            array('value'=>'IM Fell French Canon SC', 'label'=>Mage::helper('themeoptions')->__('IM Fell French Canon SC')),
            array('value'=>'IM Fell Great Primer', 'label'=>Mage::helper('themeoptions')->__('IM Fell Great Primer')),
            array('value'=>'IM Fell Great Primer SC', 'label'=>Mage::helper('themeoptions')->__('IM Fell Great Primer SC')),
            array('value'=>'Iceberg', 'label'=>Mage::helper('themeoptions')->__('Iceberg')),
            array('value'=>'Iceland', 'label'=>Mage::helper('themeoptions')->__('Iceland')),
            array('value'=>'Inconsolata', 'label'=>Mage::helper('themeoptions')->__('Inconsolata')),
            array('value'=>'Inder', 'label'=>Mage::helper('themeoptions')->__('Inder')),
            array('value'=>'Indie Flower', 'label'=>Mage::helper('themeoptions')->__('Indie Flower')),
            array('value'=>'Inika', 'label'=>Mage::helper('themeoptions')->__('Inika')),
            array('value'=>'Irish Grover', 'label'=>Mage::helper('themeoptions')->__('Irish Grover')),
            array('value'=>'Istok Web', 'label'=>Mage::helper('themeoptions')->__('Istok Web')),
            array('value'=>'Italianno', 'label'=>Mage::helper('themeoptions')->__('Italianno')),
            array('value'=>'Jim Nightshade', 'label'=>Mage::helper('themeoptions')->__('Jim Nightshade')),
            array('value'=>'Jockey One', 'label'=>Mage::helper('themeoptions')->__('Jockey One')),
            array('value'=>'Josefin Sans', 'label'=>Mage::helper('themeoptions')->__('Josefin Sans')),
            array('value'=>'Josefin Slab', 'label'=>Mage::helper('themeoptions')->__('Josefin Slab')),
            array('value'=>'Judson', 'label'=>Mage::helper('themeoptions')->__('Judson')),
            array('value'=>'Julee', 'label'=>Mage::helper('themeoptions')->__('Julee')),
            array('value'=>'Junge', 'label'=>Mage::helper('themeoptions')->__('Junge')),
            array('value'=>'Jura', 'label'=>Mage::helper('themeoptions')->__('Jura')),
            array('value'=>'Just Another Hand', 'label'=>Mage::helper('themeoptions')->__('Just Another Hand')),
            array('value'=>'Just Me Again Down Here', 'label'=>Mage::helper('themeoptions')->__('Just Me Again Down Here')),
            array('value'=>'Kameron', 'label'=>Mage::helper('themeoptions')->__('Kameron')),
            array('value'=>'Kaushan Script', 'label'=>Mage::helper('themeoptions')->__('Kaushan Script')),
            array('value'=>'Kelly Slab', 'label'=>Mage::helper('themeoptions')->__('Kelly Slab')),
            array('value'=>'Kenia', 'label'=>Mage::helper('themeoptions')->__('Kenia')),
            array('value'=>'Knewave', 'label'=>Mage::helper('themeoptions')->__('Knewave')),
            array('value'=>'Kotta One', 'label'=>Mage::helper('themeoptions')->__('Kotta One')),
            array('value'=>'Kranky', 'label'=>Mage::helper('themeoptions')->__('Kranky')),
            array('value'=>'Kreon', 'label'=>Mage::helper('themeoptions')->__('Kreon')),
            array('value'=>'Kristi', 'label'=>Mage::helper('themeoptions')->__('Kristi')),
            array('value'=>'La Belle Aurore', 'label'=>Mage::helper('themeoptions')->__('La Belle Aurore')),
            array('value'=>'Lancelot', 'label'=>Mage::helper('themeoptions')->__('Lancelot')),
            array('value'=>'Lato', 'label'=>Mage::helper('themeoptions')->__('Lato')),
            array('value'=>'League Script', 'label'=>Mage::helper('themeoptions')->__('League Script')),
            array('value'=>'Leckerli One', 'label'=>Mage::helper('themeoptions')->__('Leckerli One')),
            array('value'=>'Lekton', 'label'=>Mage::helper('themeoptions')->__('Lekton')),
            array('value'=>'Lemon', 'label'=>Mage::helper('themeoptions')->__('Lemon')),
            array('value'=>'Lilita One', 'label'=>Mage::helper('themeoptions')->__('Lilita One')),
            array('value'=>'Limelight', 'label'=>Mage::helper('themeoptions')->__('Limelight')),
            array('value'=>'Linden Hill', 'label'=>Mage::helper('themeoptions')->__('Linden Hill')),
            array('value'=>'Lobster', 'label'=>Mage::helper('themeoptions')->__('Lobster')),
            array('value'=>'Lobster Two', 'label'=>Mage::helper('themeoptions')->__('Lobster Two')),
            array('value'=>'Lora', 'label'=>Mage::helper('themeoptions')->__('Lora')),
            array('value'=>'Love Ya Like A Sister', 'label'=>Mage::helper('themeoptions')->__('Love Ya Like A Sister')),
            array('value'=>'Loved by the King', 'label'=>Mage::helper('themeoptions')->__('Loved by the King')),
            array('value'=>'Luckiest Guy', 'label'=>Mage::helper('themeoptions')->__('Luckiest Guy')),
            array('value'=>'Lusitana', 'label'=>Mage::helper('themeoptions')->__('Lusitana')),
            array('value'=>'Lustria', 'label'=>Mage::helper('themeoptions')->__('Lustria')),
            array('value'=>'Macondo', 'label'=>Mage::helper('themeoptions')->__('Macondo')),
            array('value'=>'Macondo Swash Caps', 'label'=>Mage::helper('themeoptions')->__('Macondo Swash Caps')),
            array('value'=>'Magra', 'label'=>Mage::helper('themeoptions')->__('Magra')),
            array('value'=>'Maiden Orange', 'label'=>Mage::helper('themeoptions')->__('Maiden Orange')),
            array('value'=>'Mako', 'label'=>Mage::helper('themeoptions')->__('Mako')),
            array('value'=>'Marck Script', 'label'=>Mage::helper('themeoptions')->__('Marck Script')),
            array('value'=>'Marko One', 'label'=>Mage::helper('themeoptions')->__('Marko One')),
            array('value'=>'Marmelad', 'label'=>Mage::helper('themeoptions')->__('Marmelad')),
            array('value'=>'Marvel', 'label'=>Mage::helper('themeoptions')->__('Marvel')),
            array('value'=>'Mate', 'label'=>Mage::helper('themeoptions')->__('Mate')),
            array('value'=>'Mate SC', 'label'=>Mage::helper('themeoptions')->__('Mate SC')),
            array('value'=>'Maven Pro', 'label'=>Mage::helper('themeoptions')->__('Maven Pro')),
            array('value'=>'Meddon', 'label'=>Mage::helper('themeoptions')->__('Meddon')),
            array('value'=>'MedievalSharp', 'label'=>Mage::helper('themeoptions')->__('MedievalSharp')),
            array('value'=>'Medula One', 'label'=>Mage::helper('themeoptions')->__('Medula One')),
            array('value'=>'Megrim', 'label'=>Mage::helper('themeoptions')->__('Megrim')),
            array('value'=>'Merienda One', 'label'=>Mage::helper('themeoptions')->__('Merienda One')),
            array('value'=>'Merriweather', 'label'=>Mage::helper('themeoptions')->__('Merriweather')),
            array('value'=>'Metamorphous', 'label'=>Mage::helper('themeoptions')->__('Metamorphous')),
            array('value'=>'Metrophobic', 'label'=>Mage::helper('themeoptions')->__('Metrophobic')),
            array('value'=>'Michroma', 'label'=>Mage::helper('themeoptions')->__('Michroma')),
            array('value'=>'Miltonian', 'label'=>Mage::helper('themeoptions')->__('Miltonian')),
            array('value'=>'Miltonian Tattoo', 'label'=>Mage::helper('themeoptions')->__('Miltonian Tattoo')),
            array('value'=>'Miniver', 'label'=>Mage::helper('themeoptions')->__('Miniver')),
            array('value'=>'Miss Fajardose', 'label'=>Mage::helper('themeoptions')->__('Miss Fajardose')),
            array('value'=>'Modern Antiqua', 'label'=>Mage::helper('themeoptions')->__('Modern Antiqua')),
            array('value'=>'Molengo', 'label'=>Mage::helper('themeoptions')->__('Molengo')),
            array('value'=>'Monofett', 'label'=>Mage::helper('themeoptions')->__('Monofett')),
            array('value'=>'Monoton', 'label'=>Mage::helper('themeoptions')->__('Monoton')),
            array('value'=>'Monsieur La Doulaise', 'label'=>Mage::helper('themeoptions')->__('Monsieur La Doulaise')),
            array('value'=>'Montaga', 'label'=>Mage::helper('themeoptions')->__('Montaga')),
            array('value'=>'Montez', 'label'=>Mage::helper('themeoptions')->__('Montez')),
            array('value'=>'Montserrat', 'label'=>Mage::helper('themeoptions')->__('Montserrat')),
            array('value'=>'Mountains of Christmas', 'label'=>Mage::helper('themeoptions')->__('Mountains of Christmas')),
            array('value'=>'Mr Bedfort', 'label'=>Mage::helper('themeoptions')->__('Mr Bedfort')),
            array('value'=>'Mr Dafoe', 'label'=>Mage::helper('themeoptions')->__('Mr Dafoe')),
            array('value'=>'Mr De Haviland', 'label'=>Mage::helper('themeoptions')->__('Mr De Haviland')),
            array('value'=>'Mrs Saint Delafield', 'label'=>Mage::helper('themeoptions')->__('Mrs Saint Delafield')),
            array('value'=>'Mrs Sheppards', 'label'=>Mage::helper('themeoptions')->__('Mrs Sheppards')),
            array('value'=>'Muli', 'label'=>Mage::helper('themeoptions')->__('Muli')),
            array('value'=>'Neucha', 'label'=>Mage::helper('themeoptions')->__('Neucha')),
            array('value'=>'Neuton', 'label'=>Mage::helper('themeoptions')->__('Neuton')),
            array('value'=>'News Cycle', 'label'=>Mage::helper('themeoptions')->__('News Cycle')),
            array('value'=>'Niconne', 'label'=>Mage::helper('themeoptions')->__('Niconne')),
            array('value'=>'Nixie One', 'label'=>Mage::helper('themeoptions')->__('Nixie One')),
            array('value'=>'Nobile', 'label'=>Mage::helper('themeoptions')->__('Nobile')),
            array('value'=>'Norican', 'label'=>Mage::helper('themeoptions')->__('Norican')),
            array('value'=>'Nosifer', 'label'=>Mage::helper('themeoptions')->__('Nosifer')),
            array('value'=>'Nothing You Could Do', 'label'=>Mage::helper('themeoptions')->__('Nothing You Could Do')),
            array('value'=>'Noticia Text', 'label'=>Mage::helper('themeoptions')->__('Noticia Text')),
            array('value'=>'Nova Cut', 'label'=>Mage::helper('themeoptions')->__('Nova Cut')),
            array('value'=>'Nova Flat', 'label'=>Mage::helper('themeoptions')->__('Nova Flat')),
            array('value'=>'Nova Mono', 'label'=>Mage::helper('themeoptions')->__('Nova Mono')),
            array('value'=>'Nova Oval', 'label'=>Mage::helper('themeoptions')->__('Nova Oval')),
            array('value'=>'Nova Round', 'label'=>Mage::helper('themeoptions')->__('Nova Round')),
            array('value'=>'Nova Script', 'label'=>Mage::helper('themeoptions')->__('Nova Script')),
            array('value'=>'Nova Slim', 'label'=>Mage::helper('themeoptions')->__('Nova Slim')),
            array('value'=>'Nova Square', 'label'=>Mage::helper('themeoptions')->__('Nova Square')),
            array('value'=>'Numans', 'label'=>Mage::helper('themeoptions')->__('Numans')),
            array('value'=>'Nunito', 'label'=>Mage::helper('themeoptions')->__('Nunito')),
            array('value'=>'Old Standard TT', 'label'=>Mage::helper('themeoptions')->__('Old Standard TT')),
            array('value'=>'Oldenburg', 'label'=>Mage::helper('themeoptions')->__('Oldenburg')),
            array('value'=>'Open Sans', 'label'=>Mage::helper('themeoptions')->__('Open Sans')),
            array('value'=>'Open Sans Condensed', 'label'=>Mage::helper('themeoptions')->__('Open Sans Condensed')),
            array('value'=>'Orbitron', 'label'=>Mage::helper('themeoptions')->__('Orbitron')),
            array('value'=>'Original Surfer', 'label'=>Mage::helper('themeoptions')->__('Original Surfer')),
            array('value'=>'Oswald', 'label'=>Mage::helper('themeoptions')->__('Oswald')),
            array('value'=>'Over the Rainbow', 'label'=>Mage::helper('themeoptions')->__('Over the Rainbow')),
            array('value'=>'Overlock', 'label'=>Mage::helper('themeoptions')->__('Overlock')),
            array('value'=>'Overlock SC', 'label'=>Mage::helper('themeoptions')->__('Overlock SC')),
            array('value'=>'Ovo', 'label'=>Mage::helper('themeoptions')->__('Ovo')),
            array('value'=>'PT Sans', 'label'=>Mage::helper('themeoptions')->__('PT Sans')),
            array('value'=>'PT Sans Caption', 'label'=>Mage::helper('themeoptions')->__('PT Sans Caption')),
            array('value'=>'PT Sans Narrow', 'label'=>Mage::helper('themeoptions')->__('PT Sans Narrow')),
            array('value'=>'PT Serif', 'label'=>Mage::helper('themeoptions')->__('PT Serif')),
            array('value'=>'PT Serif Caption', 'label'=>Mage::helper('themeoptions')->__('PT Serif Caption')),
            array('value'=>'Pacifico', 'label'=>Mage::helper('themeoptions')->__('Pacifico')),
            array('value'=>'Parisienne', 'label'=>Mage::helper('themeoptions')->__('Parisienne')),
            array('value'=>'Passero One', 'label'=>Mage::helper('themeoptions')->__('Passero One')),
            array('value'=>'Passion One', 'label'=>Mage::helper('themeoptions')->__('Passion One')),
            array('value'=>'Patrick Hand', 'label'=>Mage::helper('themeoptions')->__('Patrick Hand')),
            array('value'=>'Patua One', 'label'=>Mage::helper('themeoptions')->__('Patua One')),
            array('value'=>'Paytone One', 'label'=>Mage::helper('themeoptions')->__('Paytone One')),
            array('value'=>'Permanent Marker', 'label'=>Mage::helper('themeoptions')->__('Permanent Marker')),
            array('value'=>'Petrona', 'label'=>Mage::helper('themeoptions')->__('Petrona')),
            array('value'=>'Philosopher', 'label'=>Mage::helper('themeoptions')->__('Philosopher')),
            array('value'=>'Piedra', 'label'=>Mage::helper('themeoptions')->__('Piedra')),
            array('value'=>'Pinyon Script', 'label'=>Mage::helper('themeoptions')->__('Pinyon Script')),
            array('value'=>'Plaster', 'label'=>Mage::helper('themeoptions')->__('Plaster')),
            array('value'=>'Play', 'label'=>Mage::helper('themeoptions')->__('Play')),
            array('value'=>'Playball', 'label'=>Mage::helper('themeoptions')->__('Playball')),
            array('value'=>'Playfair Display', 'label'=>Mage::helper('themeoptions')->__('Playfair Display')),
            array('value'=>'Podkova', 'label'=>Mage::helper('themeoptions')->__('Podkova')),
            array('value'=>'Poller One', 'label'=>Mage::helper('themeoptions')->__('Poller One')),
            array('value'=>'Poly', 'label'=>Mage::helper('themeoptions')->__('Poly')),
            array('value'=>'Pompiere', 'label'=>Mage::helper('themeoptions')->__('Pompiere')),
            array('value'=>'Port Lligat Sans', 'label'=>Mage::helper('themeoptions')->__('Port Lligat Sans')),
            array('value'=>'Port Lligat Slab', 'label'=>Mage::helper('themeoptions')->__('Port Lligat Slab')),
            array('value'=>'Prata', 'label'=>Mage::helper('themeoptions')->__('Prata')),
            array('value'=>'Princess Sofia', 'label'=>Mage::helper('themeoptions')->__('Princess Sofia')),
            array('value'=>'Prociono', 'label'=>Mage::helper('themeoptions')->__('Prociono')),
            array('value'=>'Puritan', 'label'=>Mage::helper('themeoptions')->__('Puritan')),
            array('value'=>'Quantico', 'label'=>Mage::helper('themeoptions')->__('Quantico')),
            array('value'=>'Quattrocento', 'label'=>Mage::helper('themeoptions')->__('Quattrocento')),
            array('value'=>'Quattrocento Sans', 'label'=>Mage::helper('themeoptions')->__('Quattrocento Sans')),
            array('value'=>'Questrial', 'label'=>Mage::helper('themeoptions')->__('Questrial')),
            array('value'=>'Quicksand', 'label'=>Mage::helper('themeoptions')->__('Quicksand')),
            array('value'=>'Qwigley', 'label'=>Mage::helper('themeoptions')->__('Qwigley')),
            array('value'=>'Radley', 'label'=>Mage::helper('themeoptions')->__('Radley')),
            array('value'=>'Raleway', 'label'=>Mage::helper('themeoptions')->__('Raleway')),
            array('value'=>'Rammetto One', 'label'=>Mage::helper('themeoptions')->__('Rammetto One')),
            array('value'=>'Rancho', 'label'=>Mage::helper('themeoptions')->__('Rancho')),
            array('value'=>'Rationale', 'label'=>Mage::helper('themeoptions')->__('Rationale')),
            array('value'=>'Redressed', 'label'=>Mage::helper('themeoptions')->__('Redressed')),
            array('value'=>'Reenie Beanie', 'label'=>Mage::helper('themeoptions')->__('Reenie Beanie')),
            array('value'=>'Ribeye', 'label'=>Mage::helper('themeoptions')->__('Ribeye')),
            array('value'=>'Ribeye Marrow', 'label'=>Mage::helper('themeoptions')->__('Ribeye Marrow')),
            array('value'=>'Righteous', 'label'=>Mage::helper('themeoptions')->__('Righteous')),
            array('value'=>'Rochester', 'label'=>Mage::helper('themeoptions')->__('Rochester')),
            array('value'=>'Rock Salt', 'label'=>Mage::helper('themeoptions')->__('Rock Salt')),
            array('value'=>'Rokkitt', 'label'=>Mage::helper('themeoptions')->__('Rokkitt')),
            array('value'=>'Ropa Sans', 'label'=>Mage::helper('themeoptions')->__('Ropa Sans')),
            array('value'=>'Rosario', 'label'=>Mage::helper('themeoptions')->__('Rosario')),
            array('value'=>'Rouge Script', 'label'=>Mage::helper('themeoptions')->__('Rouge Script')),
            array('value'=>'Ruda', 'label'=>Mage::helper('themeoptions')->__('Ruda')),
            array('value'=>'Ruge Boogie', 'label'=>Mage::helper('themeoptions')->__('Ruge Boogie')),
            array('value'=>'Ruluko', 'label'=>Mage::helper('themeoptions')->__('Ruluko')),
            array('value'=>'Ruslan Display', 'label'=>Mage::helper('themeoptions')->__('Ruslan Display')),
            array('value'=>'Ruthie', 'label'=>Mage::helper('themeoptions')->__('Ruthie')),
            array('value'=>'Sail', 'label'=>Mage::helper('themeoptions')->__('Sail')),
            array('value'=>'Salsa', 'label'=>Mage::helper('themeoptions')->__('Salsa')),
            array('value'=>'Sancreek', 'label'=>Mage::helper('themeoptions')->__('Sancreek')),
            array('value'=>'Sansita One', 'label'=>Mage::helper('themeoptions')->__('Sansita One')),
            array('value'=>'Sarina', 'label'=>Mage::helper('themeoptions')->__('Sarina')),
            array('value'=>'Satisfy', 'label'=>Mage::helper('themeoptions')->__('Satisfy')),
            array('value'=>'Schoolbell', 'label'=>Mage::helper('themeoptions')->__('Schoolbell')),
            array('value'=>'Shadows Into Light', 'label'=>Mage::helper('themeoptions')->__('Shadows Into Light')),
            array('value'=>'Shanti', 'label'=>Mage::helper('themeoptions')->__('Shanti')),
            array('value'=>'Share', 'label'=>Mage::helper('themeoptions')->__('Share')),
            array('value'=>'Shojumaru', 'label'=>Mage::helper('themeoptions')->__('Shojumaru')),
            array('value'=>'Short Stack', 'label'=>Mage::helper('themeoptions')->__('Short Stack')),
            array('value'=>'Sigmar One', 'label'=>Mage::helper('themeoptions')->__('Sigmar One')),
            array('value'=>'Signika', 'label'=>Mage::helper('themeoptions')->__('Signika')),
            array('value'=>'Signika Negative', 'label'=>Mage::helper('themeoptions')->__('Signika Negative')),
            array('value'=>'Sirin Stencil', 'label'=>Mage::helper('themeoptions')->__('Sirin Stencil')),
            array('value'=>'Six Caps', 'label'=>Mage::helper('themeoptions')->__('Six Caps')),
            array('value'=>'Slackey', 'label'=>Mage::helper('themeoptions')->__('Slackey')),
            array('value'=>'Smokum', 'label'=>Mage::helper('themeoptions')->__('Smokum')),
            array('value'=>'Smythe', 'label'=>Mage::helper('themeoptions')->__('Smythe')),
            array('value'=>'Sniglet', 'label'=>Mage::helper('themeoptions')->__('Sniglet')),
            array('value'=>'Snippet', 'label'=>Mage::helper('themeoptions')->__('Snippet')),
            array('value'=>'Sofia', 'label'=>Mage::helper('themeoptions')->__('Sofia')),
            array('value'=>'Sonsie One', 'label'=>Mage::helper('themeoptions')->__('Sonsie One')),
            array('value'=>'Sorts Mill Goudy', 'label'=>Mage::helper('themeoptions')->__('Sorts Mill Goudy')),
            array('value'=>'Special Elite', 'label'=>Mage::helper('themeoptions')->__('Special Elite')),
            array('value'=>'Spicy Rice', 'label'=>Mage::helper('themeoptions')->__('Spicy Rice')),
            array('value'=>'Spinnaker', 'label'=>Mage::helper('themeoptions')->__('Spinnaker')),
            array('value'=>'Spirax', 'label'=>Mage::helper('themeoptions')->__('Spirax')),
            array('value'=>'Squada One', 'label'=>Mage::helper('themeoptions')->__('Squada One')),
            array('value'=>'Stardos Stencil', 'label'=>Mage::helper('themeoptions')->__('Stardos Stencil')),
            array('value'=>'Stint Ultra Condensed', 'label'=>Mage::helper('themeoptions')->__('Stint Ultra Condensed')),
            array('value'=>'Stint Ultra Expanded', 'label'=>Mage::helper('themeoptions')->__('Stint Ultra Expanded')),
            array('value'=>'Stoke', 'label'=>Mage::helper('themeoptions')->__('Stoke')),
            array('value'=>'Sue Ellen Francisco', 'label'=>Mage::helper('themeoptions')->__('Sue Ellen Francisco')),
            array('value'=>'Sunshiney', 'label'=>Mage::helper('themeoptions')->__('Sunshiney')),
            array('value'=>'Supermercado One', 'label'=>Mage::helper('themeoptions')->__('Supermercado One')),
            array('value'=>'Swanky and Moo Moo', 'label'=>Mage::helper('themeoptions')->__('Swanky and Moo Moo')),
            array('value'=>'Syncopate', 'label'=>Mage::helper('themeoptions')->__('Syncopate')),
            array('value'=>'Tangerine', 'label'=>Mage::helper('themeoptions')->__('Tangerine')),
            array('value'=>'Telex', 'label'=>Mage::helper('themeoptions')->__('Telex')),
            array('value'=>'Tenor Sans', 'label'=>Mage::helper('themeoptions')->__('Tenor Sans')),
            array('value'=>'Terminal Dosis', 'label'=>Mage::helper('themeoptions')->__('Terminal Dosis')),
            array('value'=>'The Girl Next Door', 'label'=>Mage::helper('themeoptions')->__('The Girl Next Door')),
            array('value'=>'Tienne', 'label'=>Mage::helper('themeoptions')->__('Tienne')),
            array('value'=>'Tinos', 'label'=>Mage::helper('themeoptions')->__('Tinos')),
            array('value'=>'Titan One', 'label'=>Mage::helper('themeoptions')->__('Titan One')),
            array('value'=>'Trade Winds', 'label'=>Mage::helper('themeoptions')->__('Trade Winds')),
            array('value'=>'Trochut', 'label'=>Mage::helper('themeoptions')->__('Trochut')),
            array('value'=>'Trykker', 'label'=>Mage::helper('themeoptions')->__('Trykker')),
            array('value'=>'Tulpen One', 'label'=>Mage::helper('themeoptions')->__('Tulpen One')),
            array('value'=>'Ubuntu', 'label'=>Mage::helper('themeoptions')->__('Ubuntu')),
            array('value'=>'Ubuntu Condensed', 'label'=>Mage::helper('themeoptions')->__('Ubuntu Condensed')),
            array('value'=>'Ubuntu Mono', 'label'=>Mage::helper('themeoptions')->__('Ubuntu Mono')),
            array('value'=>'Ultra', 'label'=>Mage::helper('themeoptions')->__('Ultra')),
            array('value'=>'Uncial Antiqua', 'label'=>Mage::helper('themeoptions')->__('Uncial Antiqua')),
            array('value'=>'UnifrakturCook', 'label'=>Mage::helper('themeoptions')->__('UnifrakturCook')),
            array('value'=>'UnifrakturMaguntia', 'label'=>Mage::helper('themeoptions')->__('UnifrakturMaguntia')),
            array('value'=>'Unkempt', 'label'=>Mage::helper('themeoptions')->__('Unkempt')),
            array('value'=>'Unlock', 'label'=>Mage::helper('themeoptions')->__('Unlock')),
            array('value'=>'Unna', 'label'=>Mage::helper('themeoptions')->__('Unna')),
            array('value'=>'VT323', 'label'=>Mage::helper('themeoptions')->__('VT323')),
            array('value'=>'Varela', 'label'=>Mage::helper('themeoptions')->__('Varela')),
            array('value'=>'Varela Round', 'label'=>Mage::helper('themeoptions')->__('Varela Round')),
            array('value'=>'Vast Shadow', 'label'=>Mage::helper('themeoptions')->__('Vast Shadow')),
            array('value'=>'Vibur', 'label'=>Mage::helper('themeoptions')->__('Vibur')),
            array('value'=>'Vidaloka', 'label'=>Mage::helper('themeoptions')->__('Vidaloka')),
            array('value'=>'Viga', 'label'=>Mage::helper('themeoptions')->__('Viga')),
            array('value'=>'Volkhov', 'label'=>Mage::helper('themeoptions')->__('Volkhov')),
            array('value'=>'Vollkorn', 'label'=>Mage::helper('themeoptions')->__('Vollkorn')),
            array('value'=>'Voltaire', 'label'=>Mage::helper('themeoptions')->__('Voltaire')),
            array('value'=>'Waiting for the Sunrise', 'label'=>Mage::helper('themeoptions')->__('Waiting for the Sunrise')),
            array('value'=>'Wallpoet', 'label'=>Mage::helper('themeoptions')->__('Wallpoet')),
            array('value'=>'Walter Turncoat', 'label'=>Mage::helper('themeoptions')->__('Walter Turncoat')),
            array('value'=>'Wellfleet', 'label'=>Mage::helper('themeoptions')->__('Wellfleet')),
            array('value'=>'Wire One', 'label'=>Mage::helper('themeoptions')->__('Wire One')),
            array('value'=>'Yanone Kaffeesatz', 'label'=>Mage::helper('themeoptions')->__('Yanone Kaffeesatz')),
            array('value'=>'Yellowtail', 'label'=>Mage::helper('themeoptions')->__('Yellowtail')),
            array('value'=>'Yeseva One', 'label'=>Mage::helper('themeoptions')->__('Yeseva One')),
            array('value'=>'Yesteryear', 'label'=>Mage::helper('themeoptions')->__('Yesteryear')),
            array('value'=>'Zeyada', 'label'=>Mage::helper('themeoptions')->__('Zeyada')),
            array('value'=>'Oswald', 'label'=>Mage::helper('themeoptions')->__('Oswald'))               
        );
    }

}
?>