<ul class="level0">
<li class="level1 nav-1-1 first parent"><a href="{{config path="web/unsecure/base_url"}}printable-diy/baby-templates"><span> Baby Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-1-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/baby-templates/baby-shower-invitations"> <span>Shower Invitations</span></a></li>
<li class="level2 nav-1-1-2"><a href="{{config path="web/unsecure/base_url"}}printable-diy/baby-templates/birth-announcements"> <span>Birth Announcements</span></a></li>
<li class="level2 nav-1-1-3"><a href="{{config path="web/unsecure/base_url"}}printable-diy/baby-templates/baby-s-1st-birthday"> <span>1st Birthday</span></a></li>
<li class="level2 nav-1-1-4 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/baby-templates/baptism-christening"> <span>Baptism/Christening</span></a></li>
</ul>
<a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates"><span> Holiday Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-6-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/oscar-party"> <span>Oscar Party</span></a></li>
<li class="level2 nav-1-6-2"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/4th-of-july-templates"> <span>4th of July</span></a></li>
<li class="level2 nav-1-6-3"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/halloween"> <span>Halloween Party</span></a></li>
<li class="level2 nav-1-6-4"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/thanksgiving"> <span>Thanksgiving</span></a></li>
<li class="level2 nav-1-6-5"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/christmas"> <span>Christmas</span></a></li>
<li class="level2 nav-1-6-6 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/holiday-templates/valentines-day"> <span>Valentines Day</span></a></li>
</ul>
</li>
<li class="level1 nav-1-2 parent"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates"> <span>Birthday Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-2-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/kds-party"> <span>Kids Party</span></a></li>
<li class="level2 nav-1-2-2"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/13th-birthday-barmitzvah"> <span>Bar Mitzvah Invitations</span></a></li>
<li class="level2 nav-1-2-3"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/18-party"> <span>18th Birthday Invites</span></a></li>
<li class="level2 nav-1-2-4"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/sweet-16-party"> <span>Sweet 16 Party</span></a></li>
<li class="level2 nav-1-2-5"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/21-party"> <span>21st Birthday Invites</span></a></li>
<li class="level2 nav-1-2-6"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/40-party"> <span>40th Birthday Invites</span></a></li>
<li class="level2 nav-1-2-7"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/50-party"> <span>50th Birthday Invites</span></a></li>
<li class="level2 nav-1-2-8"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/tea-party-invites"> <span>Tea Party</span></a></li>
<li class="level2 nav-1-2-9 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/birthday-templates/general"> <span>General Birthday</span></a></li>
</ul>
<a href="{{config path="web/unsecure/base_url"}}printable-diy/graduation-templates"> <span>Graduation Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-3-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/graduation-templates/announcements"> <span>Graduation Announcements</span></a></li>
<li class="level2 nav-1-3-2 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/graduation-templates/graduation-party"> <span>Graduation Party</span></a></li>
</ul>
</li>
<li class="level1 nav-1-4 parent"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates"><span> Wedding Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-4-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/bachelorette-party-invitations"> <span>Bachelorette Party</span></a></li>
<li class="level2 nav-1-4-2"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/wedding-shower-invitations"> <span>Bridal Shower</span></a></li>
<li class="level2 nav-1-4-3"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/long-fold-programs"> <span>Long Fold Programs</span></a></li>
<li class="level2 nav-1-4-4"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/reception-menus"> <span>Reception Menus</span></a></li>
<li class="level2 nav-1-4-5"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/invitations"> <span>Elegant Invitations</span></a></li>
<li class="level2 nav-1-4-6"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/reception-placecards"> <span>Reception Placecards</span></a></li>
<li class="level2 nav-1-4-7"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/rsvp-cards"> <span>RSVP Cards</span></a></li>
<li class="level2 nav-1-4-8"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/wedding-programs"> <span>Letter Single Fold</span></a></li>
<li class="level2 nav-1-4-9"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/graduated-fold-programs"> <span>Graduated Fold Programs</span></a></li>
<li class="level2 nav-1-4-10 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/wedding-templates/save-the-date"> <span>Save The Date</span></a></li>
</ul>
</li>
<li class="level1 nav-1-5 parent"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs"><span> Funeral Templates</span></a>
<ul class="level1">
<li class="level2 nav-1-5-1 first"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/funeral-cards"> <span>Funeral Cards</span></a></li>
<li class="level2 nav-1-5-2"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/bifold-program-templates"> <span>Letter Single Fold</span></a></li>
<li class="level2 nav-1-5-3"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/memorial-bookmarks"> <span>Memorial Bookmarks</span></a></li>
<li class="level2 nav-1-5-4"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/4-page-graduated-fold"> <span>4 Page Graduated Fold</span></a></li>
<li class="level2 nav-1-5-5"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/legal-single-fold-programs"> <span>Legal Single Fold</span></a></li>
<li class="level2 nav-1-5-6"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/tri-fold-brochures"> <span>Tri Fold Brochures</span></a></li>
<li class="level2 nav-1-5-7"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/funeral-flyer-sheets"> <span>Flyer Sheets</span></a></li>
<li class="level2 nav-1-5-8"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/a4-order-of-service-sheets-templates"> <span>A4 Service Sheets</span></a></li>
<li class="level2 nav-1-5-9"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/announcement-postcards"> <span>Announcement Postcards</span></a></li>
<li class="level2 nav-1-5-10"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/large-tabloid-booklet-templates"> <span>Large Tabloid Booklets</span></a></li>
<li class="level2 nav-1-5-11"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/pet-memorials"> <span>Pet Memorial Cards</span></a></li>
<li class="level2 nav-1-5-12"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/gatefold-programs"> <span>Gatefold Programs</span></a></li>
<li class="level2 nav-1-5-13"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/custom-cover-programs"> <span>Custom Cover Programs</span></a></li>
<li class="level2 nav-1-5-14 last"><a href="{{config path="web/unsecure/base_url"}}printable-diy/funeral-programs/monogram-programs"> <span>Monogram Programs</span></a></li>
</ul>
</li>
</ul>